### ISSUE TITLE
Matching Syriaca URIs for persons and works through the Zanetti Fiche Numbers

### ISSUE THREAD

**Issue by davidamichelson** [srophe/persons#3]
Sample records for this workflow:
http://wwwb.library.vanderbilt.edu/person/1494
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1140 (http://syriaca.org/work/1140 = BHS: 976)

Here is the workflow:
* We need to update the Saints Persons XSLT to grab the numbers in the columns marked "Fiche". At present the XSLT is not grabbing them at all. It used to grab them as IDNO elements but I commented that out at line 293. It is supposed to grab them at https://github.com/srophe/persons/blob/master/xsl/saint-spreadsheet2tei.xsl#L440 but there is a problem there, I think because there is still a reference to Z1 which no longer exists as a column header.

* These Fiche numbers should each be used in the following ways:
**In the person record at the path /tei:TEI/tei:text/tei:body/tei:listPerson/tei:person/tei:bibl/tei:ptr/@target[http://syriaca.org/bibl/650], these numbers need to be inserted as the text node for /tei:TEI/tei:text/tei:body/tei:listPerson/tei:person/tei:bibl/tei:citedRange/@unit[entry]:
```<bibl xml:id="bib[URI]-1">
                  <title level="m" xml:lang="la">Biblioteca Hagiographica Syriaca</title>
                  <ptr target="http://syriaca.org/bibl/649"/>
                  <citedRange unit="entry">[Fiche], [Fiche]</citedRange>
               </bibl>```

Next, we need a query need to associate person URIs with Fiche numbers and then look these Fiche numbers up in the works XML files where they can be found in the text nodes of /TEI/text/body/bibl/idno/@type[BHS]. For example ```<idno type="BHS">976</idno>```

In each work TEI record, we then need to insert a reference back to the Syriaca person URI where the Fiche number originated.

At the path /TEI/text/body/ in work/1140 this XML should be this:
```<listRelation><relation name="dcterms:subject" active="http://syriaca.org/work/1140" passive="http://syriaca.org/person/1494" source="#bib1140-1"/><listRelation>```

Note: as this runs there may be relations in the same work created by this script. So the query should check to see if a listRelation already exists and if so insert a relation element inside.

Finally we will then want to write a script that uses this listRelation in Works to insert a reference to the work back in persons as an attestation:

In the Persons TEI it should look like this (I am not sure if the source is right, it should be whatever source in the record corresponds to http://syriaca.org/bibl/649):

This attestation should be inserted at the end of the document just before the first /tei:TEI/tei:text/tei:body/tei:listPerson/tei:person/tei:bibl

```                    <event type="attestation" xml:id="attestation1494-1" source="#bib1494-1">
                        <p xml:lang="en">[Name from headword of person/1494] is commemorated in <title>[Title headword from work/1140]</title>.</p>
                    </event>```

**Comment by davidamichelson** [comment]
@nathangibson Could you look over this please and let me know your thoughts. Also please remind me we should discuss what vocabularies to use. You can see I am using dc:subject for now.

**Comment by davidamichelson** [comment]
@wsalesky Okay, I think this is ready.

**Comment by davidamichelson** [comment]
@wsalesky Okay I made a few edits to the XSLT myself, but there is a problem at https://github.com/srophe/persons/blob/master/xsl/saint-spreadsheet2tei.xsl#L440 where I think we still have the old Column Name z1, it should now be Fiche? Can you try to fix please? Thanks!

**Comment by wsalesky** [comment]
Remove indo/@type=BHS only in persons,

**Comment by wsalesky** [comment]
@davidamichelson Would we want to include a ref attribute in the title of the attestation? ex:
```
<event type="attestation" xml:id="attestation1494-1" source="#bib1494-1"> 
    <p xml:lang="en">[Name from headword of person/1494] is commemorated in  
        <title ref="http://syriaca.org/work/WORKURI">[Title headword from work/1140]</title>.
    </p>
</event>
```

**Comment by davidamichelson** [comment]
Yes please!!!!

**Comment by wsalesky** [comment]
@davidamichelson Please spot check records.

**Comment by davidamichelson** [comment]
@wsalesky Just reviewing this. Great work! Just realizing we did not give you text for visualization of this in the HTML.
Here is what we would like:

In works we would like to visualize the related persons in two ways.

First, in the current works TEI data <relation> please change all instances of name="dcterms:subject" to name="syriaca:commemorated". This is a new relation we will add to the module.

Then this should be visualized below where we visualize Author in the top box.
Please add a new heading:"Persons Featured" (also it looks like we need to standardize the use or lack of colons, let's leave them off).

Then the prose should look like this 

Persons Featured
*Persons commemorated [person(s) headword from URI] 
*Persons highlighted in this text: [person(s) headword from URI] 

[The first line is determined by use of syriaca:commemorates, it will need to have a variant for multiple names, "This work commemorates [person headword from URI], [person headword from URI]" etc for an unlimited number of names"

The second line is determined by use of dcterms:subject, it will need the same use of commas for multiples.

Lastly, we still need to visualize works in persons as above in the first part of this issue. Do you need input on that?

Thanks for all you do!

**Comment by wsalesky** [comment]
Okay, thanks. I will work on this today.

**Comment by wsalesky** [comment]
Add URI's 
Yōlēṭā is commemorated in Cyriacus and Julietta (text) [syriaca.org/work/395].1
Yōlēṭā is commemorated in Cyriacus and Julietta (text) [syriaca.org/work/1251].1

**Comment by davidamichelson** [comment]
Okay, finally spot checking this and unfortunately there seem to be some missing person records.

For example: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1861 should link to person 1311 but that person does not load. Is there a person 1311 tei? Perhaps the query was not run on some documents?

**Comment by wsalesky** [comment]
There is no 1311.  Is there a link to 1311 on this page, I didn't see it?
There is a 1311 in the incomplete folder:
 https://github.com/srophe/persons/blob/master/new-saints-data/incomplete/tei/1311.xml

**Comment by davidamichelson** [comment]
Ah, that is it! I forgot about the incompletes. I can't even remember why
they are excluded. Let's discuss next week.

**Comment by wsalesky** [comment]
Some of them do not have headwords I believe.

**Comment by davidamichelson** [comment]
Okay, we should, however, run this matching script on them anyway, but I
see that will be a problem. Let's discuss in person. Do you have time today?

**Comment by davidamichelson** [comment]
@wsalesky Okay, now we need to run this script on the revisionDesc status="incomplete" records but I am closing this as I have opened it in https://github.com/srophe/srophe-app-data/issues/329
