### ISSUE TITLE
@ef instead of @ref

### ISSUE THREAD

**Issue by nathangibson** [srophe/persons#4]
Unfortunately https://github.com/srophe/persons/blob/master/xsl/saint-spreadsheet2tei.xsl#L681 has "ef" instead of "ref" for Carlson's resp statement. I guess we'll need to rerun the transform? Or just find and replace?

**Comment by wsalesky** [comment]
A find and replace would be better. I ran a bunch of xqueries on the data yesterday and updated the data in draft data. If @davidamichelson is okay with it, I think we should consider the data in draft data the canonical form, and make all future changes to the TEI not the xslt.

**Comment by nathangibson** [comment]
Yes, I think @davidamichelson wanted it that way. Do you want me to go ahead and do the find and replace?

**Comment by wsalesky** [comment]
I just pushed the new data.
