### ISSUE TITLE
Mapping author matches back into works

### ISSUE THREAD

**Issue by nathangibson** [srophe/persons#5]
@wsalesky, not done with the author matching yet, but wanted to check before I get too far if the following will work OK for getting the author refs back into the work records:
https://github.com/srophe/persons/blob/master/xml/spreadsheets/authors-from-hagiography-NER-all-names-reconciled.xml#L6

For authors we already have in our database, I've just added a ref attribute to the author element, like so:
```
<author ref="http://syriaca.org/person/13" xml:lang="fr" source="#bib1000-1">Éphrem</author> 
```
I used find and replace to add that ref to each of the authors having that name. 

We should be able to identify the URI of each work record it goes back into by parsing the source attribute (removing the "#bib" and the "-1"), right? 

For authors we do not yet have in our database, I have provided a temporary xml:id and supplied the information that should go into the new person record that is created, including an English persName and sometimes a note type="abstract" or idno. Any of that info that needs to be sourced, I sourced to a Syriaca URI. For example,
```
<author source="#bib1039-1" xml:id="Amphiloque-d’Iconium">
                    <persName xml:lang="fr">Amphiloque d’Iconium</persName>
                    <persName xml:lang="en-x-gedsh" source="http://syriaca.org/bibl/233">Amphilochius of Iconium</persName>
                    <idno>https://en.wikipedia.org/wiki/Amphilochius_of_Iconium</idno>
                </author>
```
Where there are multiple works with one of these new authors, I have put a ref to the xml:id (e.g., "#Amphiloque-d’Iconium"). 

So I don't know if creating those new persons and putting their URIs into the works as refs can be automated. If not, no big deal, or if I need to do something differently here, let me know. Thanks!

**Comment by wsalesky** [comment]
@nathangibson, that looks fine to me. And yes, this can be automated. 
Let me know when it is ready to go, I can write the script or coach you through it, depending on your level of interest in xquery.

**Comment by davidamichelson** [comment]
@nathangibson Is this issue done? If so this repo would be issue free which would be nice to close it ;)

**Comment by nathangibson** [comment]
Yes, done ;-)
