### ISSUE TITLE
Updating incomplete persons records to prepare for move to app-data repo

### ISSUE THREAD

**Issue by davidamichelson** [srophe/persons#6]
@wsalesky Please update these records: https://github.com/srophe/persons/tree/master/new-saints-data/incomplete/tei

With the following:

Please designate the [1] xml:lang="en" as the syriaca-headword
Please update the revision desc to status="draft"
Please run a script to update the title (/tei:TEI/tei:teiHeader/tei:fileDesc/tei:titleStmt/tei:title) to reflect the new "en" head word and no Syriac.

**Comment by wsalesky** [comment]
@davidamichelson  See above commit. 
Review and merge branch issue6 when approved.

**Comment by davidamichelson** [comment]
Thanks! They  mostly look good, but I realized I needed to edit the names and abstracts a bit. Can we rerun the script that changes the title after I edit some of the en headwords?

**Comment by wsalesky** [comment]
Yes

**Comment by davidamichelson** [comment]
@wsalesky and @nathangibson The incomplete saints are moved over to appdata repo and marked with revisionDesc @status="incomplete"

Winona the web hooks aren't loading them, could you manually do it please?

thanks,
Dave

**Comment by wsalesky** [comment]
They should be up now.
Webhooks are working again, but they time out for large requests. Still
troubleshooting this.
-Winona

**Comment by davidamichelson** [comment]
Thanks!
